description = "Ubuntu bionic base image with buildpacks for Java"

[lifecycle]
  version = "0.4.0"

[[buildpacks]]
  id = "org.cloudfoundry.openjdk"
  uri = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.0.56.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.buildsystem"
  uri = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.0.125.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.jvmapplication"
  uri = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.0.78.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.procfile"
  uri = "https://storage.googleapis.com/cnb-buildpacks/procfile-cnb/org.cloudfoundry.procfile-1.0.39.tgz"

[[buildpacks]]
  id = "am.ik.buildpacks.jvmkill"
  uri = "https://github.com/making/jvmkill-cnb/releases/download/0.1.0/jvmkill-cnb-0.1.0.tgz"

[[buildpacks]]
  id = "am.ik.buildpacks.memorycalculator"
  uri = "https://github.com/making/memory-calculator-cnb/releases/download/0.1.1/memory-calculator-cnb-0.1.1.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.debug"
  uri = "https://storage.googleapis.com/cnb-buildpacks/debug-cnb/org.cloudfoundry.debug-1.0.100.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.jmx"
  uri = "https://storage.googleapis.com/cnb-buildpacks/jmx-cnb/org.cloudfoundry.jmx-1.0.101.tgz"

[[order]]
  [[order.group]]
    id = "org.cloudfoundry.openjdk"
    version = "1.0.56"

  [[order.group]]
    id = "org.cloudfoundry.buildsystem"
    version = "1.0.125"
    optional = true 

  [[order.group]]
    id = "org.cloudfoundry.jvmapplication"
    version = "1.0.78"

  [[order.group]]
    id = "org.cloudfoundry.procfile"
    version = "1.0.39"
    optional = true

  [[order.group]]
    id = "am.ik.buildpacks.jvmkill"
    version = "0.1.0"
    optional = true 

  [[order.group]]
    id = "am.ik.buildpacks.memorycalculator"
    version = "0.1.1"
    optional = true 

  [[order.group]]
    id = "org.cloudfoundry.debug"
    version = "1.0.100"
    optional = true
 
  [[order.group]]
    id = "org.cloudfoundry.jmx"
    version = "1.0.101"
    optional = true

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "cloudfoundry/build:base-cnb"
  run-image = "cloudfoundry/run:base-cnb"
